name: psjh-epic-sd-ssl-lbvserver
description: "Epic SlicerDicer Server SSL Load-Balancing - Customized for PSJH Epic StyleBooks."
display-name: "Epic SlicerDicer Server SSL LB vServer StyleBook"
author: Nathan Joseph
namespace: com.psjh.epic.stylebooks
schema-version: "1.0" 
version: "1.0" 
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "11.1"
  - 
    namespace: com.psjh.epic.stylebooks
    prefix: psjh-epic
    version: "1.0"
parameters-default-sources:
  - psjh-epic::psjh-epic-lb-helper-params
  - psjh-epic::psjh-epic-ssl-helper-params
parameters:
  -
    name: httpprofile
    label: HTTP Profile Name
    description: "Optionally, provide the name of an existing HTTP Profile to use for the configuration."
    type: string
    required: false 
  -
    name: SDmonitorVersion
    label: Use New SlicerDicer Monitor Type
    description: "Select this option if the SlicerDicer Application is running August 2018 or later, or Epic 2018 with special update C8409293. Doing so will utilize the new recommended Monitor configuration."
    type: object
    required: false
    gui:
      collapse_pane: true
    parameters:
      -
        name: SDapp
        label: SlicerDicer Web Application
        description: "Provide the name of the SlicerDicer Application supported by this configuration for monitoring. EX: /<SDapp>/Health/StatusCheck"
        type: string
        required: true
substitutions:
components:
  -
    name: SD-lbvserver-comp
    type: ns::lbvserver
    properties:
        name: str("lb_SD_%{$parameters.AppDescription}%_SSL")
        servicetype: SSL
        ipv46: $parameters.ip
        port: 443
        lbmethod: ROUNDROBIN
        persistencetype: COOKIEINSERT
        timeout: 0
        tcpprofilename?: $parameters.vserver-tcp-profile
        httpprofilename?: $parameters.httpprofile
        redirectfromport?: $parameters.SSLRedirectPort
        httpsredirecturl?: $parameters.SSLRedirectURL
        comment: str("SlicerDicer SSL LB vServer Configuration - %{$parameters.AppDescription}%") 
    components:
      -
        name: SD-sslvserver-sslprofile
        type: ns::sslvserver
        condition: $parameters.SSLProfile
        properties:
          sslprofile: $parameters.SSLProfile
          vservername: $parent.properties.name
      -
        name: SD-servicegroup-comp
        type: ns::servicegroup
        properties:
          servicegroupname: str("svcg_SD_%{$parameters.AppDescription}%_SSL")
          servicetype: SSL
          downstateflush: DISABLED
          sp: str("OFF")
          useproxyport: str("YES")
          tcpprofilename?: $parameters.servicegroup-tcp-profile
          httpprofilename?: $parameters.httpprofile
          comment?: str("SlicerDicer SSL LB Service Group Configuration - %{$parameters.AppDescription}%") 
        components:
          -
            name: SD-lbvserver-svcg-binding
            type: ns::lbvserver_servicegroup_binding
            properties:
              name: $parent.parent.properties.name
              servicegroupname: $parent.properties.servicegroupname
          -
            name: SD-server-members
            type: ns::server
            repeat: $parameters.svc-servers
            repeat-item: server
            repeat-condition: $server.add-server
            properties:
              name: str("srv_%{$server.svc-name}%_%{$server.ip}%")
              ipaddress: $server.ip
          - 
            name: SD-svcg-ip-members
            type: ns::servicegroup_servicegroupmember_binding
            repeat: $parameters.svc-servers
            repeat-item: server
            properties: 
              servername: str("srv_%{$server.svc-name}%_%{$server.ip}%")
              port: 443
              servicegroupname: $parent.properties.servicegroupname
          -
            name: SD-monitor-svcg-binding-comp
            type: ns::servicegroup_lbmonitor_binding
            condition: not $parameters.SDmonitorVersion
            properties:
              servicegroupname: $parent.properties.servicegroupname
              monitor_name: str("https-ecv")
      - 
        name: vserver-certs-bindings
        type: psjh-epic::psjh-vserver-certs-binds
        condition: $parameters.certificates
        properties:
          certificates: $parameters.certificates
          vserver-name: $parent.properties.name
      - 
        name: vserver-certs-bindings-existing
        type: ns::sslvserver_sslcertkey_binding
        condition: $parameters.certificates-existing
        properties:
          certkeyname: $parameters.certificates-existing
          vservername: $parent.properties.name
  -
    name: SD-monitor-comp
    type: ns::lbmonitor
    condition: $parameters.SDmonitorVersion
    properties:
      monitorname: str("mon_SD_%{$parameters.AppDescription}%_HTTP-ECV")
      type: HTTP-ECV
      send: str("GET /%{$parameters.SDmonitorVersion.SDapp}%/Health/StatusCheck")
      recv: str("true")
      secure: str("YES")
      interval: 30
      resptimeout: 10
      retries: 3
    components:
      -
        name: SD-monitor-svcg-binding-comp-new
        type: ns::servicegroup_lbmonitor_binding
        properties:
          servicegroupname: $components.SD-lbvserver-comp.components.SD-servicegroup-comp.properties.servicegroupname
          monitor_name: $parent.properties.monitorname